services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-networks

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${PORT}:3000"
    depends_on:
      - mongo
    env_file:
      - .env

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-builder
    networks:
      - app-networks

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - frontend-builder
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - app-networks

networks:
  app-network:
    driver: bridge
